### ISSUE TITLE
PyPI?

### ISSUE THREAD

**Issue by ghost** [danielyule/naya#1]
Cool project, thanks Daniel!

I'd love to add a feature to [JLTool](https://github.com/cathalgarvey/jltool) for converting from array-of-objects to newline-delimited-JSON, and `naya` looks like a great tool for one of these directions.

I *could* just clone the code into JLTool and vendor it (with attribution of course!), which would require no effort from you. The "ecosystem" way of doing this, though, would be to add `naya` as a dependency in JLTool's `setup.py` script, instead.

Would you be interested in setting this up on PyPI, so I can add it accordingly as a dependency? Feel free to say no, I'll just vendor it no problem. :)

**Comment by danielyule** [comment]
Hi Cathal,

As it turns out, I had completely forgotten that I had written this, and was very surprised that it seems to be fairly complete.  So, thank you for reminding me!

I can throw it up on PyPI, no problem.  It will probably be up within an hour or so.

**Comment by ghost** [comment]
Awesome, thanks! Most of the comparably code out there either tries to decode every frame (stupidly inefficient, if virtually bug-proof) or only emits parsing events, not the actual objects. Despite the name, `naya` represents a rare construction that efficiently emits objects! :)

On 10 November 2016 17:53:08 GMT+00:00, danielyule notifications@github.com wrote:

> Hi Cathal,
> 
> As it turns out, I had completely forgotten that I had written this,
> and was very surprised that it seems to be fairly complete.  So, thank
> you for reminding me!
> 
> I can throw it up on PyPI, no problem.  It will probably be up within
> an hour or so.
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/danielyule/naya/issues/1#issuecomment-259759715

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by danielyule** [comment]
OK, the code has been posted to PyPI at version 1.0.0.  Let me know if there are any problems using it.

**Comment by ghost** [comment]
Thanks! :)

On 10 November 2016 18:31:55 GMT+00:00, danielyule notifications@github.com wrote:

> OK, the code has been posted to PyPI at version 1.0.0.  Let me know if
> there are any problems using it.
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/danielyule/naya/issues/1#issuecomment-259769202

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
